### ISSUE TITLE
Kotlin error

### ISSUE THREAD

**Issue by Ralle001** [sebdehne/SmartHomeServer#2]
First I setup the webapp with npm and it seems like it starts without any issue. But after I try to start the kotlin app from the Main.kt in IDEA it gives me a TimeoutException. I changed all the IPs to the right IP but left the ports default. My webserver starts at port 3000 and I can open it and see the default website. But it always says "Connecting" and never "Connected".
The error:
```
Exception in thread "main" java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at com.dehnes.smarthome.victron.DalyBmsDataLogger.reconnect(DalyBmsDataLogger.kt:57)
	at com.dehnes.smarthome.Configuration.init(Configuration.kt:152)
	at com.dehnes.smarthome.MainKt.main(Main.kt:25)
	at com.dehnes.smarthome.MainKt.main(Main.kt)
```
Do I need to change the ports as well? Or because I don't have the Mqtt setup it causes a problem?

**Comment by thuz** [comment]
> First I setup the webapp with npm and it seems like it starts without any issue. But after I try to start the kotlin app from the Main.kt in IDEA it gives me a TimeoutException. I changed all the IPs to the right IP but left the ports default. My webserver starts at port 3000 and I can open it and see the default website. But it always says "Connecting" and never "Connected". The error:
> 
> ```
> Exception in thread "main" java.util.concurrent.TimeoutException
> 	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
> 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
> 	at com.dehnes.smarthome.victron.DalyBmsDataLogger.reconnect(DalyBmsDataLogger.kt:57)
> 	at com.dehnes.smarthome.Configuration.init(Configuration.kt:152)
> 	at com.dehnes.smarthome.MainKt.main(Main.kt:25)
> 	at com.dehnes.smarthome.MainKt.main(Main.kt)
> ```
> 
> Do I need to change the ports as well? Or because I don't have the Mqtt setup it causes a problem?




Same issue here, did you ever manage to fix it
?

**Comment by sebdehne** [comment]
Sorry guys - SmartHomeServer is my private substitution for [home-assist](https://www.home-assistant.io/) and I have not spend the effort/time to polish the code such that it is _easy_ for other people to run it as well (without modifications). I just do not have the time.

Feel free to use the code as is, but I am unable to provide support for it.
